meta:
  environment: dev
  application: Banking System
  version: v1
log:
  level: DEBUG
http:
  host: 0.0.0.0
  port: 8000
database:
  host: localhost
  port: 5432
  username: postgres
  password: root
  dbname: banking-system-backend
  schema: public
jwt:
  token:
otel:
  address: http://localhost:14268/api/traces
